runtime: php74

handlers:
    - url: /cryptostatus/hourly
      script: auto

env_variables:
    TWITTER_API_CONSUMER_KEY: twitter_api_consumer_key
    TWITTER_API_CONSUMER_SECRET: twitter_api_consumer_secret
    TWITTER_API_ACCESS_TOKEN: twitter_api_access_token
    TWITTER_API_ACCESS_TOKEN_SECRET: twitter_api_access_token_secret
